import React, { createContext, useContext, useState } from 'react';

interface LanguageContextType {
  language: 'en' | 'pt';
  setLanguage: (lang: 'en' | 'pt') => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'auth.welcome': 'Welcome',
    'dashboard.title': 'Strategic Planning',
    'dashboard.purposeDriven': 'Purpose Driven',
    'dashboard.makingImpact': 'Making Impact',
    'dashboard.creatingValue': 'Creating Value',

    'vision.title': 'Vision',
    'vision.edit': 'Edit Vision',
    'vision.save': 'Save Vision',
    'vision.placeholder': 'Enter your company vision...',
    'vision.empty': 'No vision statement defined yet.',
    'vision.inspiring': 'Inspiring the Future',
    'vision.driving': 'Driving Innovation',
    'vision.impact': 'Creating Impact',

    'mission.title': 'Mission',
    'mission.edit': 'Edit Mission',
    'mission.save': 'Save Mission',
    'mission.placeholder': 'Enter your company mission...',
    'mission.empty': 'No mission statement defined yet.',

    'values.title': 'Values',
    'values.new': 'Add New Value',
    'values.edit': 'Edit Value',
    'values.save': 'Save Changes',
    'values.description': 'Value Description',
    'values.meaning': 'Value Meaning',
    'values.placeholder': 'Enter value description...',
    'values.meaningPlaceholder': 'Describe what this value means...',
    'values.showMeaning': 'Show meaning',
    'values.noMeaning': 'No meaning provided',
    'values.empty': 'No values defined yet',
    'values.getStarted': 'Get started by adding your company\'s core values.',

    'perspectives.title': 'Perspectives',
    'perspectives.new': 'Add New Perspective',
    'perspectives.edit': 'Edit Perspective',
    'perspectives.save': 'Save Changes',
    'perspectives.description': 'Perspective Description',
    'perspectives.placeholder': 'Enter perspective description...',
    'perspectives.empty': 'No perspectives defined yet',
    'perspectives.getStarted': 'Get started by adding your strategic perspectives.',
    'perspectives.firstNew': 'Add First Perspective',

    'goals.title': 'Goals',
    'goals.new': 'New Goal',
    'goals.edit': 'Edit Goal',
    'goals.description': 'Description',
    'goals.descriptionPlaceholder': 'Enter goal description...',
    'goals.perspective': 'Perspective',
    'goals.selectPerspective': 'Select perspective...',
    'goals.startDate': 'Start Date',
    'goals.endDate': 'End Date',
    'goals.timeline': 'Timeline',
    'goals.completion': 'Completion',
    'goals.actions': 'Actions',
    'goals.noGoals': 'No goals',
    'goals.getStarted': 'Get started by creating a new goal.',
    'goals.confirmDelete': 'Are you sure you want to delete this goal?',
    'goals.unknownPerspective': 'Unknown Perspective',
    'goals.objectivesCount': 'Objectives',
    'goals.linkedObjectives': 'Linked Objectives',
    'goals.manualProgress': 'Manual Progress',
    'goals.achievedProgress': 'Achieved Progress',

    'objectives.title': 'Strategic Objectives',
    'objectives.new': 'New Objective',
    'objectives.edit': 'Edit Objective',
    'objectives.description': 'Description',
    'objectives.descriptionPlaceholder': 'Enter objective description...',
    'objectives.relatedGoal': 'Related Goal',
    'objectives.selectGoal': 'Select a goal...',
    'objectives.startDate': 'Start Date',
    'objectives.endDate': 'End Date',
    'objectives.timeline': 'Timeline',
    'objectives.progress': 'Progress',
    'objectives.actions': 'Actions',
    'objectives.noObjectives': 'No objectives',
    'objectives.getStarted': 'Get started by creating a new objective.',
    'objectives.confirmDelete': 'Are you sure you want to delete this objective?',
    'objectives.unknownGoal': 'Unknown Goal',
    'objectives.manual': 'Manual',
    'objectives.fromPlans': 'From Plans',
    'objectives.manualProgress': 'Manual Progress',

    'actionPlans.title': 'Action Plans',
    'actionPlans.new': 'New Action Plan',
    'actionPlans.edit': 'Edit Action Plan',
    'actionPlans.description': 'Description',
    'actionPlans.descriptionPlaceholder': 'Enter action plan description...',
    'actionPlans.howTo': 'How to Execute',
    'actionPlans.howToPlaceholder': 'Describe how this plan will be executed...',
    'actionPlans.responsible': 'Responsible Person',
    'actionPlans.selectResponsible': 'Select responsible person...',
    'actionPlans.relatedObjective': 'Related Objective',
    'actionPlans.selectObjective': 'Select related objective...',
    'actionPlans.startDate': 'Start Date',
    'actionPlans.endDate': 'End Date',
    'actionPlans.timeline': 'Timeline',
    'actionPlans.progress': 'Progress',
    'actionPlans.actions': 'Actions',
    'actionPlans.noPlans': 'No action plans',
    'actionPlans.getStarted': 'Get started by creating a new action plan.',
    'actionPlans.confirmDelete': 'Are you sure you want to delete this action plan?',
    'actionPlans.unknownUser': 'Unknown User',
    'actionPlans.unknownObjective': 'Unknown Objective',
    'actionPlans.checkIns': 'Check-ins',
    'actionPlans.addCheckIn': 'Add Check-in',
    'actionPlans.checkInDate': 'Date',
    'actionPlans.checkInDescription': 'Description',
    'actionPlans.checkInProgress': 'Progress',
    'actionPlans.checkInDescriptionPlaceholder': 'Describe the progress made...',
    'actionPlans.saveCheckIn': 'Save Check-in',

    'swot.title': 'SWOT Analysis',
    'swot.strengths': 'Strengths',
    'swot.weaknesses': 'Weaknesses',
    'swot.opportunities': 'Opportunities',
    'swot.threats': 'Threats',
    'swot.newItemPlaceholder': 'Add new item...',
    'swot.confirmDelete': 'Are you sure you want to delete this item?',

    'sidebar.dashboard': 'Dashboard',
    'sidebar.companies': 'Companies',
    'sidebar.users': 'Users',
    'sidebar.settings': 'Settings',
    'sidebar.vision': 'Vision',
    'sidebar.mission': 'Mission',
    'sidebar.values': 'Values',
    'sidebar.strategicPlanning': 'Strategic Planning',
    'sidebar.overview': 'Overview',
    'sidebar.strategicMap': 'Strategic Map',
    'sidebar.swot': 'SWOT Analysis',
    'sidebar.perspectives': 'Perspectives',
    'sidebar.goals': 'Goals',
    'sidebar.objectives': 'Objectives',
    'sidebar.actionPlans': 'Action Plans',
    'sidebar.logout': 'Logout',

    'common.save': 'Save Changes',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.create': 'Create',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.update': 'Update',
    'common.loading': 'Loading...',
  },
  pt: {
    'auth.welcome': 'Bem-vindo',
    'dashboard.title': 'Planejamento Estratégico',
    'dashboard.purposeDriven': 'Orientado por Propósito',
    'dashboard.makingImpact': 'Gerando Impacto',
    'dashboard.creatingValue': 'Criando Valor',

    'vision.title': 'Visão',
    'vision.edit': 'Editar Visão',
    'vision.save': 'Salvar Visão',
    'vision.placeholder': 'Digite a visão da sua empresa...',
    'vision.empty': 'Nenhuma declaração de visão definida ainda.',
    'vision.inspiring': 'Inspirando o Futuro',
    'vision.driving': 'Impulsionando Inovação',
    'vision.impact': 'Criando Impacto',

    'mission.title': 'Missão',
    'mission.edit': 'Editar Missão',
    'mission.save': 'Salvar Missão',
    'mission.placeholder': 'Digite a missão da sua empresa...',
    'mission.empty': 'Nenhuma declaração de missão definida ainda.',

    'values.title': 'Valores',
    'values.new': 'Adicionar Novo Valor',
    'values.edit': 'Editar Valor',
    'values.save': 'Salvar Alterações',
    'values.description': 'Descrição do Valor',
    'values.meaning': 'Significado do Valor',
    'values.placeholder': 'Digite a descrição do valor...',
    'values.meaningPlaceholder': 'Descreva o que este valor significa...',
    'values.showMeaning': 'Mostrar significado',
    'values.noMeaning': 'Nenhum significado fornecido',
    'values.empty': 'Nenhum valor definido ainda',
    'values.getStarted': 'Comece adicionando os valores fundamentais da sua empresa.',

    'perspectives.title': 'Perspectivas',
    'perspectives.new': 'Adicionar Nova Perspectiva',
    'perspectives.edit': 'Editar Perspectiva',
    'perspectives.save': 'Salvar Alterações',
    'perspectives.description': 'Descrição da Perspectiva',
    'perspectives.placeholder': 'Digite a descrição da perspectiva...',
    'perspectives.empty': 'Nenhuma perspectiva definida ainda',
    'perspectives.getStarted': 'Comece adicionando suas perspectivas estratégicas.',
    'perspectives.firstNew': 'Adicionar Primeira Perspectiva',

    'goals.title': 'Metas',
    'goals.new': 'Nova Meta',
    'goals.edit': 'Editar Meta',
    'goals.description': 'Descrição',
    'goals.descriptionPlaceholder': 'Digite a descrição da meta...',
    'goals.perspective': 'Perspectiva',
    'goals.selectPerspective': 'Selecione a perspectiva...',
    'goals.startDate': 'Data Inicial',
    'goals.endDate': 'Data Final',
    'goals.timeline': 'Período',
    'goals.completion': 'Conclusão',
    'goals.actions': 'Ações',
    'goals.noGoals': 'Sem metas',
    'goals.getStarted': 'Comece criando uma nova meta.',
    'goals.confirmDelete': 'Tem certeza que deseja excluir esta meta?',
    'goals.unknownPerspective': 'Perspectiva Desconhecida',
    'goals.objectivesCount': 'Objetivos',
    'goals.linkedObjectives': 'Objetivos Vinculados',
    'goals.manualProgress': 'Progresso Manual',
    'goals.achievedProgress': 'Progresso Alcançado',

    'objectives.title': 'Objetivos Estratégicos',
    'objectives.new': 'Novo Objetivo',
    'objectives.edit': 'Editar Objetivo',
    'objectives.description': 'Descrição',
    'objectives.descriptionPlaceholder': 'Digite a descrição do objetivo...',
    'objectives.relatedGoal': 'Meta Relacionada',
    'objectives.selectGoal': 'Selecione uma meta...',
    'objectives.startDate': 'Data Inicial',
    'objectives.endDate': 'Data Final',
    'objectives.timeline': 'Período',
    'objectives.progress': 'Progresso',
    'objectives.actions': 'Ações',
    'objectives.noObjectives': 'Sem objetivos',
    'objectives.getStarted': 'Comece criando um novo objetivo.',
    'objectives.confirmDelete': 'Tem certeza que deseja excluir este objetivo?',
    'objectives.unknownGoal': 'Meta Desconhecida',
    'objectives.manual': 'Manual',
    'objectives.fromPlans': 'Dos Planos',
    'objectives.manualProgress': 'Progresso Manual',

    'actionPlans.title': 'Planos de Ação',
    'actionPlans.new': 'Novo Plano de Ação',
    'actionPlans.edit': 'Editar Plano de Ação',
    'actionPlans.description': 'Descrição',
    'actionPlans.descriptionPlaceholder': 'Digite a descrição do plano de ação...',
    'actionPlans.howTo': 'Como Executar',
    'actionPlans.howToPlaceholder': 'Descreva como este plano será executado...',
    'actionPlans.responsible': 'Responsável',
    'actionPlans.selectResponsible': 'Selecione o responsável...',
    'actionPlans.relatedObjective': 'Objetivo Relacionado',
    'actionPlans.selectObjective': 'Selecione o objetivo relacionado...',
    'actionPlans.startDate': 'Data Inicial',
    'actionPlans.endDate': 'Data Final',
    'actionPlans.timeline': 'Período',
    'actionPlans.progress': 'Progresso',
    'actionPlans.actions': 'Ações',
    'actionPlans.noPlans': 'Sem planos de ação',
    'actionPlans.getStarted': 'Comece criando um novo plano de ação.',
    'actionPlans.confirmDelete': 'Tem certeza que deseja excluir este plano de ação?',
    'actionPlans.unknownUser': 'Usuário Desconhecido',
    'actionPlans.unknownObjective': 'Objetivo Desconhecido',
    'actionPlans.checkIns': 'Check-ins',
    'actionPlans.addCheckIn': 'Adicionar Check-in',
    'actionPlans.checkInDate': 'Data',
    'actionPlans.checkInDescription': 'Descrição',
    'actionPlans.checkInProgress': 'Progresso',
    'actionPlans.checkInDescriptionPlaceholder': 'Descreva o progresso realizado...',
    'actionPlans.saveCheckIn': 'Salvar Check-in',

    'swot.title': 'Análise SWOT',
    'swot.strengths': 'Forças',
    'swot.weaknesses': 'Fraquezas',
    'swot.opportunities': 'Oportunidades',
    'swot.threats': 'Ameaças',
    'swot.newItemPlaceholder': 'Adicionar novo item...',
    'swot.confirmDelete': 'Tem certeza que deseja excluir este item?',

    'sidebar.dashboard': 'Dashboard',
    'sidebar.companies': 'Empresas',
    'sidebar.users': 'Usuários',
    'sidebar.settings': 'Configurações',
    'sidebar.vision': 'Visão',
    'sidebar.mission': 'Missão',
    'sidebar.values': 'Valores',
    'sidebar.strategicPlanning': 'Planejamento Estratégico',
    'sidebar.overview': 'Visão Geral',
    'sidebar.strategicMap': 'Mapa Estratégico',
    'sidebar.swot': 'Análise SWOT',
    'sidebar.perspectives': 'Perspectivas',
    'sidebar.goals': 'Metas',
    'sidebar.objectives': 'Objetivos',
    'sidebar.actionPlans': 'Planos de Ação',
    'sidebar.logout': 'Sair',

    'common.save': 'Salvar Alterações',
    'common.cancel': 'Cancelar',
    'common.edit': 'Editar',
    'common.delete': 'Excluir',
    'common.create': 'Criar',
    'common.add': 'Adicionar',
    'common.remove': 'Remover',
    'common.update': 'Atualizar',
    'common.loading': 'Carregando...',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<'en' | 'pt'>('pt');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}